Features
OscarFMdev/BudgetWizard pull request #5
Opened 2023-02-17 04:34 UTC by OscarFMdev

# PR description: 📄 

Details of this project:
- Use ruby gems as software packages system.
- Install Ruby on Rails framework.
- Understand Rails RESTful design and router.
- Use controllers to handle requests and render empty views.
- Use params from browser request in a safe way.
- Use preprocessed html file with embedded Ruby code.
- Use layouts and templates for shared content.
- Use database migration files to maintain database schema.
- Use validations for models.
- Secure app from n+1 problems.
- Understand what ORM is.
- Write SQL queries with ActiveRecord.
- Set up associations between models.
- Build a webapp that requires the user to log in.
- Use devise gem for authentication.
- Limit access to webapp resources based on authorization rules.
- Analyze in writing why you have made a coding choice using one structure over another.

2023-02-17 05:39 UTC, andersonlebon requested changes
## Hi @OscarFMdev 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-02-17 05:39 UTC, andersonlebon commented on README.md
> +- [Video documentation](https://www.loom.com/share/ac09caece5d44647afebc939f68a82c9)
- [ ] NIce video presentation that highlights all the features of your project, however, it should also highlight a piece of the code that you found interesting or you are proud of making. This will give your project a strong documentation.

2023-02-17 05:39 UTC, andersonlebon commented on app/assets/stylesheets/application.css
> +  color: white;
- [ ] Nice work including many functionalities (image storage, editing....), however, you need to follow the original design template as part of the requirements. check how your pages should look exactly

## The signup page 
<img width="321" alt="image" src="https://user-images.githubusercontent.com/65068771/219556247-24b9b07c-2d33-41a3-9fcc-a76f80ecaab7.png">

## the welcome page 
<img width="321" alt="image" src="https://user-images.githubusercontent.com/65068771/219556444-2876435d-f96a-4667-908e-22bdb385bd8c.png">

## Login page 
<img width="321" alt="image" src="https://user-images.githubusercontent.com/65068771/219556655-7b4b393b-c19b-473a-8f87-b3c098972e44.png">

## group page 
<img width="321" alt="image" src="https://user-images.githubusercontent.com/65068771/219556864-73616d4b-afca-4c79-874e-2ecbf166ed48.png">

## entities page 
<img width="321" alt="image" src="https://user-images.githubusercontent.com/65068771/219557461-b04def01-4025-4939-80e1-bf75d7237742.png">


Note: please make sure the design much the template by using the same  
* Colors
* Typography: font face, size, and weight.
* Layout: composition and space between elements.

>

2023-02-18 09:40 UTC, danielufeli approved these changes
Hi @OscarFMdev ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![ChopApproveCopApproveGIF](https://user-images.githubusercontent.com/48371156/200094064-25efa74f-2f0c-4f2f-9129-28b06b04359b.gif)

## Highlights
- Nice commits messages✔️
- Clean Code ✔️

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @danielufeli in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._ate_comments_counter`

2023-02-18 15:35 UTC, merged